---
baseurl: "https://eagleusb.github.io"

theme:
  - "terminal"
  - "cloak-email"

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true

cleandestinationdir: false
publishdir: "public"
staticdir: "static"
disablehugogeneratorinject: true
enablerobotstxt: true

pagination:
  pagerSize: 1

params:
  contentTypeName: "posts"
  themeColor: "blue"
  showMenuItems: 5
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true
  favicon: "favicon.ico"
  showLastUpdated: true
  readingTime: true
  Toc: true
  # Provide a string as a prefix for the last update date.
  # By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix: "Updated"
  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = false
  logo:
    logoText: "grumpycat tech stories."
    logoHomeLink: "/"

title: "grumpycat tech stories."
subtitle: "I like cats and engineering"
owner: "eagleusb"
keywords: "freelance, cto, devops, platform engineer, site reliability engineer, sre, lyon"
copyright: "Leslie-Alexandre DENIS"

menu:
  main:
    - identifier: "photobook"
      name: "photobook"
      url: "https://photo.eagleusb.com"
      params:
        newTab: true
    - identifier: "contact"
      name: "ping me"
      url: "/ping"
    - identifier: "resume"
      name: "resume"
      url: "/assets/resume-leslie-alexandre-denis.pdf"
      params:
        newTab: true
    - identifier: "gh"
      name: "github"
      url: "https://github.com/eagleusb"
      params:
        newTab: true
    - identifier: "linkedin"
      name: "linkedin"
      url: "https://www.linkedin.com/in/lesliealexandredenis/"
      params:
        newTab: true

languages:
  fr:
    languageName: "French"
    menuMore: "plus..."
    readMore: "lire..."
    readOtherPosts: "Read other posts"
    missingContentMessage: "Page not found..."
    missingBackButtonLabel: "Back to home page"
  en:
    languageName: "English"
    menuMore: "more..."
    readMore: "read more..."
    readOtherPosts: "+"
    missingContentMessage: "page not found..."
    missingBackButtonLabel: "back to home"
